global using FluentValidation;
global using FluentValidation.AspNetCore;
global using Mapster;
global using MapsterMapper;
global using Microsoft.AspNetCore.Authorization;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using SurveyBasket.Core.Entities;
global using SurveyBasket.Core.Service;